{{- if .Values.movieService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.movieService.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.movieService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.movieService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.movieService.name }}
    spec:
      initContainers:
        - name: wait-for-mysql
          image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
          command:
            ["sh", "-c", "until mysql -h {{ .Values.mysql.name }} -u {{ .Values.mysql.user }} -p{{ .Values.mysql.password }} -e 'SELECT 1' >/dev/null 2>&1; do echo waiting for {{ .Values.mysql.name }}; sleep 5; done"]
      containers:
        - name: {{ .Values.movieService.name }}
          image: {{ .Values.movieService.image.repository }}:{{ .Values.movieService.image.tag }}
          ports:
            - containerPort: {{ .Values.movieService.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.movieService.env.springProfilesActive }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.movieService.env.springDatasourceUrl }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.movieService.env.springDatasourceUsername }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.movieService.env.springDatasourcePassword }}
            - name: ZIPKIN_ENDPOINT
              value: {{ .Values.movieService.env.zipkinEndpoint }}
{{- end }}

